### ISSUE TITLE
bidi conflict with metalogo

### ISSUE THREAD

**Issue by maieul** [vafa/bidi#1]
The new version of bidi provides \XeLaTeX and \XeTeX commands, which makes impossible to load the metalogo package, which also defines them, but also \LuaTeX command.

May I suggest you to do a RequirePackage{metalogo} instead of defining your command? 

many thanks

**Comment by vafa** [comment]
> The new version of bidi provides \XeLaTeX and \XeTeX commands, which makes impossible to load the metalogo package, which also defines them, but also \LuaTeX command.

The `bidi` package provided the `\XeTeX` and `\XeLaTeX` macros since day one; it is not something new. All I did in the most recent version of the `bidi` package was to make these two macros robust.

> May I suggest you to do a RequirePackage{metalogo} instead of defining your command? 

I am afraid that I am not going to do anything about this; it is not `bidi`'s issue. The `bidi` package existed long before `metalogo` package and as I said it provided the `\XeTeX` and `\XeLaTeX` macros even before the `metalogo` package existed. The author of `metalogo` package failed to realize this and so I consider it a `metalogo` bug.

Indeed, several years ago Enrico Gregorio reported the same issue to me and I gave exactly the same answer. You can find its discussion [here](http://guitex.org/home/en/forum/5-tex-e-latex/57074-pacchetti-metalogo-e-bidi).

The `bidi` package already modifies over 100 packages and classes; keeping up with all these packages and classes is just insane and I am not willing to fix other packages bugs in my package. Sorry!

**Comment by maieul** [comment]
what is strange is that before the previous update of bidi, I was able to compile with metalogo + bidi...

**Comment by vafa** [comment]
> what is strange is that before the previous update of bidi, I was able to compile with metalogo + bidi...

When I produce the following minimal example

```latex
\documentclass{article}
\usepackage{metalogo}
\usepackage{bidi}
\begin{document}
\XeTeX{} \XeLaTeX{}
\end{document}
```
I get the following error

```
/usr/local/texlive/2016/texmf-dist/tex/xelatex/bidi/latex-xetex-bidi.def:118: L
aTeX Error: Command \XeTeX already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.118 ...di@reflect@box{E}}\kern-.1667em \TeX}}$}}
                                                  
? 

perhaps, this is what you meant. This is because the `bidi` package previously defined the two macros using `\def` but now it uses `\bidi@newrobustcmd` to define them so if they are already defined, you get an error. This worked before but obviously you would get `bidi`'s definition not `metalogo`'s one. The following example works for me

```latex
\documentclass{article}
\usepackage{metalogo}
\let\XeTeX\undefined
\let\XeLaTeX\undefined
\usepackage{bidi}
\begin{document}
\XeTeX{} \XeLaTeX{}
\end{document}
```
This gives you `bidi` definition. If you want `metalogo` definition, then the following example should be ok.

```latex
\documentclass{article}
\usepackage{metalogo}
\let\xetex\XeTeX
\let\xelatex\XeLaTeX
\let\XeTeX\undefined
\let\XeLaTeX\undefined
\usepackage{bidi}
\let\XeTeX\xetex
\let\XeLaTeX\xelatex
\begin{document}
\XeTeX{} \XeLaTeX{}
\end{document}
```

**Comment by maieul** [comment]
yes, that is. And so now, I understand better �
